MvcBookStore/MvcBookStore/Models/CHUDE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUDE
    {
        public CHUDE()
        {
            this.SACHes = new HashSet<SACH>();
        }
    
        public int MaCD { get; set; }
        public string TenChuDe { get; set; }
    
        public virtual ICollection<SACH> SACHes { get; set; }
    }
}

MvcBookStore/MvcBookStore/Models/NHAXUATBAN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAXUATBAN
    {
        public NHAXUATBAN()
        {
            this.SACHes = new HashSet<SACH>();
        }
    
        public int MaNXB { get; set; }
        public string TenNXB { get; set; }
        public string Diachi { get; set; }
        public string Dienthoai { get; set; }
    
        public virtual ICollection<SACH> SACHes { get; set; }
    }
}

MvcBookStore/MvcBookStore/Controllers/BookStoreController.cs
using MvcBookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PagedList;
using PagedList.Mvc;

namespace MvcBookStore.Controllers
{
    public class BookStoreController : Controller
    {
        private QLBANSACHEntities db = new QLBANSACHEntities();
        // GET: BookStore

        private List<SACH> LaySacMoi(int count)
        {
            return db.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Index(int ? page)
        {
            int pageSize = 4;
            int pageNum = (page ?? 1);
            var sachmoi = LaySacMoi(10);
            return View(sachmoi.ToPagedList(pageNum,pageSize));
        }

        public ActionResult ChuDe()
        {
            var chude = db.CHUDEs.ToList();
            return View(chude);
        }

        public ActionResult NhaXuatBan()
        {
            var chude = db.NHAXUATBANs.ToList();
            return View(chude);
        }

        public ActionResult SPTheoChuDe(int id)
        {
            var sach = db.SACHes.Where(c => c.MaCD == id).ToList();
            return View(sach);
        }
        public ActionResult SPTheoNXB(int id)
        {
            var sach = db.SACHes.Where(c => c.MaNXB == id).ToList();
            return View(sach);
        }

        public ActionResult Details(int id)
        {
            var sach = db.SACHes.Where(c => c.Masach == id).ToList();
            return View(sach.Single());
        }
    }
}

MvcBookStore/MvcBookStore/Controllers/GiohangController.cs
using MvcBookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBookStore.Controllers
{
    public class GiohangController : Controller
    {
        QLBANSACHEntities data = new QLBANSACHEntities();
        // GET: Giohang
        public ActionResult Index()
        {
            return View();
        }
        public List<GioHang> LayGioHang()
        {
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang == null)
            {
                lstGioHang = new List<GioHang>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }

        public ActionResult ThemGIoHang(int iMasach, string strUrl)
        {
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sp = lstGioHang.Find(n => n.iMasach == iMasach);
            if (sp == null)
            {
                sp = new GioHang(iMasach);
                lstGioHang.Add(sp);
                return Redirect(strUrl);
            }
            else
            {
                sp.iSoluong++;
                return Redirect(strUrl);
            }
        }

        private int TongSL()
        {
            int iTongSL = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                iTongSL = lstGioHang.Sum(n => n.iSoluong);
            }
            return iTongSL;
        }
        private double TongTien()
        {
            double iTongTien = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                iTongTien = lstGioHang.Sum(n => n.dThanhtien);
            }
            return iTongTien;
        }

        public ActionResult GioHang()
        {
            List<GioHang> lstGioHang = LayGioHang();
            if (lstGioHang.Count == 0)
            {
                return RedirectToAction("Index", "BookStore");
            }
            ViewBag.TongSL = TongSL();
            ViewBag.TongTien = TongTien();
            return View(lstGioHang);
        }

        public ActionResult GioHangPartial()
        {
            ViewBag.TongSL = TongSL();
            ViewBag.TongTien = TongTien();
            return PartialView();
        }
        public ActionResult XoaGioHang(int? iMaSP)
        {
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sp = lstGioHang.SingleOrDefault(n => n.iMasach == iMaSP);
            if(sp != null)
            {
                lstGioHang.RemoveAll(n => n.iMasach == iMaSP);
                return RedirectToAction("GioHang");
            }
            if(lstGioHang.Count == 0)
            {
                return RedirectToAction("Index", "BookStore");
            }
            return RedirectToAction("GioHang");
        }

        public ActionResult CapNhatGioHang(int? iMaSP, FormCollection f)
        {
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sp = lstGioHang.SingleOrDefault(n => n.iMasach == iMaSP);
            if (sp != null)
            {
                sp.iSoluong = int.Parse(f["txtSoLuong"].ToString());
            }
            return RedirectToAction("GioHang");
        }
        public ActionResult XoaTatCaGioHang()
        {
            List<GioHang> lstGiohang = LayGioHang();
            lstGiohang.Clear();
            return RedirectToAction("Index", "BookStore");
        }
        [HttpGet]
        public ActionResult DatHang()
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "Nguoidung");
            }
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "BookStore");
            }

            List<GioHang> lstGioHang = LayGioHang();
            ViewBag.TongSL = TongSL();
            ViewBag.TongTien = TongTien();

            return View(lstGioHang);
        }
        public ActionResult DatHang(FormCollection collection)
        {
            DONDATHANG ddh = new DONDATHANG();
            KHACHHANG kh = (KHACHHANG)Session["TaiKhoan"];
            List<GioHang> gh = LayGioHang();
            ddh.MaKH = kh.MaKH;
            ddh.Ngaydat = DateTime.Now;
            var ngayGiao = String.Format("{0:MM/dd/yyyy}", collection["NgayGiao"]);
            ddh.Ngaygiao = DateTime.Parse(ngayGiao);
            ddh.Tinhtranggiaohang = false;
            ddh.Dathanhtoan = false;
            data.DONDATHANGs.Add(ddh);
            data.SaveChanges();
            foreach(var item in gh)
            {
                CHITIETDONDATHANG ctdh = new CHITIETDONDATHANG();
                ctdh.MaDonHang = ddh.MaDonHang;
                ctdh.Masach = item.iMasach;
                ctdh.Soluong = item.iSoluong;
                ctdh.Dongia = (decimal) item.dDongia;

                data.CHITIETDONDATHANGs.Add(ctdh);
            }
            data.SaveChanges();
            Session["GioHang"] = null;
            return RedirectToAction("XacNhanDonHang", "GioHang");
        }

        public ActionResult XacNhanDonHang()
        {
            return View();
        }
    }
}

MvcBookStore/MvcBookStore/Views/BookStore/ChuDe.cshtml
@model IEnumerable<MvcBookStore.Models.CHUDE>

<div class="templatemo_content_left_section">
    <h1>Chủ đề sách</h1>
    <ul>
        @foreach (var item in Model)
        {
            <li><a href="@Url.Action("SPTheoChuDe", "BookStore", new { id = item.MaCD})">@item.TenChuDe</a></li>
        }
    </ul>
</div>

MvcBookStore/MvcBookStore/Views/BookStore/Details.cshtml
@model MvcBookStore.Models.SACH
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<style>
    #DatMua a{
        clear: both;
        background-color: red;
        color: white;
        width: 20px;
        height: 35px;
        display: block;
        float: right;
        text-align: center;
        padding-top: 10px;
        text-decoration: none;
        font-weight: bold;
    }
    #DatMua a:hover{
        background-color: gray;
        color: red;
    }
</style>
<h2>Thông tin chi tiết</h2>
<div id="templatemo_content_right">

    <h1>@Model.Tensach</h1>
    <div class="image_panel"><img src="~/Content/images/@Model.Anhbia" alt="CSS Template" width="100" height="150" /></div>
    <p>@Model.Mota</p>


    <div class="cleaner_with_height">&nbsp;</div>
</div> <!-- end of content right -->
<div class="buy_now_button">
    <a href="@Url.Action("ThemGioHang", "Giohang", new { @iMasach = Model.Masach, @strUrl = Request.Url.ToString()})">
        Đặt mua
    </a>
</div>

MvcBookStore/MvcBookStore/Views/BookStore/Index.cshtml
@using MvcBookStore.Models
@using PagedList.Mvc
@model PagedList.PagedList<SACH>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Sách mới</h2>

@foreach (var item in Model)
{
    <div class="templatemo_product_box">
        <h1>@item.Tensach</h1>
        <a href="@Url.Action("Details", "BookStore", new { id = item.Masach})">
            <img src="~/Content/images/@item.Anhbia" alt="image" width="100" height="140" />
        </a>

        <div class="product_info">
            <p>Etiam luctus. Quisque facilisis suscipit elit. Curabitur...</p>
            <h3>@item.Giaban</h3>
            <div class="buy_now_button"><a href="@Url.Action("ThemGioHang", "Giohang", new { @iMasach = item.Masach, @strUrl = Request.Url.ToString()})">Buy Now</a></div>
            <div class="detail_button"><a href="@Url.Action("Details", "BookStore", new { id = item.Masach})">Detail</a></div>
        </div>
        <div class="cleaner">&nbsp;</div>
    </div>
}


Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

<style>
    .MenuTrang {
        margin-top: 10px;
    }

        .MenuTrang li {
            display: inline-block;
            margin: 0 5px; /* Khoảng cách giữa các mục */
        }

        .MenuTrang a,
        .MenuTrang span {
            display: inline-block;
            width: 38px;
            height: 30px;
            line-height: 30px; /* Canh giữa theo chiều dọc */
            text-align: center;
            color: #fff; /* Màu chữ trắng */
            border: 1px solid white;
            border-radius: 5px; /* Bo góc */
            text-decoration: none; /* Bỏ gạch chân */
            transition: background-color 0.3s ease, color 0.3s ease; /* Hiệu ứng hover */
        }

            .MenuTrang a:hover {
                background-color: rgba(0, 123, 255, 1); /* Màu nền khi hover */
            }

        .MenuTrang .active {
            background-color: rgba(0, 123, 255, 1); /* Màu nền của mục đang chọn */
            border-radius: 5px; /* Bo góc */
            cursor: default;
        }
</style>

MvcBookStore/MvcBookStore/Views/BookStore/NhaXuatBan.cshtml
@model IEnumerable<MvcBookStore.Models.NHAXUATBAN>

<div class="templatemo_content_left_section">
    <h1>Nhà xuất bản</h1>
    <ul>
        @foreach (var item in Model)
        {
            <li><a href="@Url.Action("SPTheoNXB", "BookStore", new { id = item.MaNXB})">@item.TenNXB</a></li>
        }
    </ul>
</div>

MvcBookStore/MvcBookStore/Views/BookStore/SPTheoChuDe.cshtml
@model IEnumerable<MvcBookStore.Models.SACH>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Sách theo chủ đề</h2>
@foreach (var item in Model)
{
    <div class="templatemo_product_box">
        <h1>@item.Tensach</h1>
        <a href="@Url.Action("Details", "BookStore", new { id = item.Masach})">
            <img src="~/Content/images/@item.Anhbia" alt="image" width="100" height="140" />
        </a>

        <div class="product_info">
            <p>Etiam luctus. Quisque facilisis suscipit elit. Curabitur...</p>
            <h3>@item.Giaban</h3>
            <div class="buy_now_button"><a href="@Url.Action("ThemGioHang", "Giohang", new { @iMasach = item.Masach, @strUrl = Request.Url.ToString()})">Buy Now</a></div>
            <div class="detail_button"><a href="@Url.Action("Details", "BookStore", new { id = item.Masach})">Detail</a></div>
        </div>
        <div class="cleaner">&nbsp;</div>
    </div>
}

MvcBookStore/MvcBookStore/Views/BookStore/SPTheoNXB.cshtml
@model IEnumerable<MvcBookStore.Models.SACH>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Sách theo nhà xuất bản</h2>
@foreach (var item in Model)
{
    <div class="templatemo_product_box">
        <h1>@item.Tensach</h1>
        <a href="@Url.Action("Details", "BookStore", new { id = item.Masach})">
            <img src="~/Content/images/@item.Anhbia" alt="image" width="100" height="140" />
        </a>

        <div class="product_info">
            <p>Etiam luctus. Quisque facilisis suscipit elit. Curabitur...</p>
            <h3>@item.Giaban</h3>
            <div class="buy_now_button"><a href="@Url.Action("ThemGioHang", "Giohang", new { @iMasach = item.Masach, @strUrl = Request.Url.ToString()})">Buy Now</a></div>
            <div class="detail_button"><a href="@Url.Action("Details", "BookStore", new { id = item.Masach})">Detail</a></div>
        </div>
        <div class="cleaner">&nbsp;</div>
    </div>
}